### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8422]
**Describe the Bug**
If a docket clerk edits a Notice of Trial that was manually added to the docket record (not auto-generated via the calendaring flow), the Trial location information is not persisted in the fields, and is not available in the text of the docket entry preview.

Furthermore, if you attempt to save without re-adding the trial location, then you get a validation error indicating that you need to select a trial location again.

Note: A Notice of Trial document that is auto-generated on the docket record during the calendaring workflow does not have this same issue.  Trial location information is persisted when editing these documents.  It only appears to be happening with manually added NTD's.

**Business Impact/Reason for Severity**
Low

**In which environment did you see this bug?**
Test

**Who were you logged in as?**
Docket Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
UX research

**To Reproduce**
1. Log in as a Docket Clerk
2. Navigate to a case
3. Click Create
4. PDF Upload or Order or Notice
5. Add a Notice of Trial
6. Serve the document
7. Click Edit from the docket record
8. Notice that the trial location field is not persisted on the edit-meta page, and the trial location information is not displayed in the docket preview (see screen grab)

**Expected Behavior**
Trial location information should persist on the edit-meta screen when a Notice of trial was manually added to the docket record.

**Actual Behavior**
A clear and concise description of what actually happened.
The trial location information is not persisted on the edit-meta screen when a Notice of trial is manually added to the docket record.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/cfb780e6-a88a-4f17-bb7f-4371291f1554)

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/dcdba0c8-1330-4da4-b00c-be4cf5768e20)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by rosiehsmith** [comment]
This was resolved in https://github.com/flexion/ef-cms/issues/9968

**Comment by ttlenard** [comment]
Testing results: I notice that older Notice's of trial documents that exist on the docket record still have the blank fields.  Need Chris to chime in on whether this is ok or not.

See screen grab of blank fields on a Notice of trial that was added in blackstone 2020.  If a Notice of trial was manually added in DAWSON, then the data populates.

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/32dd0667-f47c-4052-8ead-87ea8cf87fae)

**Comment by rosiehsmith** [comment]
That's true. Legacy docket entries (`isLegacy: true`) don't appear to store the trial location or date. To get that information, it would likely require parsing these values from the document title.

**Comment by cholly75** [comment]
Already resolved, closing issue.
