### ISSUE TITLE
BUG: Document View is displaying a document when it shouldn't be

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8866]
**Describe the Bug**
I noticed that if you filter the docket record by a document type that isn't present on the docket record, and then click on the Document View tab, the document view is displaying the Petition document.  Document view probably shouldn't be displaying any documents at all, since the index on the left side of the Document View is blank.

**Business Impact/Reason for Severity**
Low

**In which environment did you see this bug?**
Test

**Who were you logged in as?**
Any Court user

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing other functionality

**To Reproduce**
1. Log in as any Court user
2. Navigate to a docket record that doesn't have all of the document types listed in the filter by dropdown (ex: exhibits)
3. Filter the docket record by one of the documents
4. You should get a message that says "There are no documents of that type"
5. Next, click on the Document View tab
6. Notice that the Petition document displays, but there are no documents listed in the left panel/
7. We probably need to adjust this so that no document is displayed

**Expected Behavior**
Since there are not documents available when the filter is applied, no documents should be displaying on the Document view tab

**Actual Behavior**
A clear and concise description of what actually happened.
The docket record was filtered by a document type that was not present on the docket record, and the user clicked on the Document View tab. Instead of a blank page, they saw the Petition document, but no documents listed on the left side panel.
 
**Screenshots**
![Image](https://github.com/user-attachments/assets/6213d2f9-ebee-4eae-bbe6-5c1d2e0b1ddd)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by cholly75** [comment]
@AnthonyLoeraTaxCourt - original issue is resolved, however selecting a filter for a document type that _does_ exist on the docket record still brings up the Petition in the Document View, despite it not being on the list of filtered items:

<img width="1433" height="779" alt="Image" src="https://github.com/user-attachments/assets/6de39f2e-5dd5-4835-bda5-a804615dec5a" />

**Comment by ttlenard** [comment]
Testing Feedback @AnthonyLoeraTaxCourt:

Looks like there are some other places now that are displaying the incorrect document or document title in the Document View.

Navigate to the following spots in DAWSON and click on one of the document links in the list. There seem to be two possible issues: 1) the document view highlights document 1 on the docket record and lists the Petition as the Document Name at the top of the page, but the document in the viewer is the correct document that you wanted to view, or 2) The document view highlights document 1 on the docket record and lists the Petition as the Document Name at the top of the page AND the document in the Document viewer IS the Petition, rather than the correct document that you clicked the link for. 

#### Broken spots:
1. Pending Report
2. Pending Motions on Judge's/Chambers Dashboard View
3. Document QC tab for Court users besides Docket and Petitions
4. Document QC In Progress (Petitions)
5. Document QC Served/Processed (Petitions)
6. Document QC Served/Processed (Docket)
7. Document QC In Progress (Docket - need to double check this one - it might be ok)

*Better check with Clerk of the Court Role and Case Services Supervisor role as well.

#### Spots that seem to be working correctly, but will want to double check:
1. Tracked Items tab (pending items)
2. Document QC Inbox (Docket)
3. Document QC inbox (Petitions)
4. Viewing docs in a message thread as attachments

**Comment by katiecissell** [comment]
@AnthonyLoeraTaxCourt I only checked the Pending Report & Pending Motions on Judge's/Chambers Dashboard View but they're still showing the wrong document/or highlighting the wrong document when I click on document links
